// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PasswordAPI.Models;

namespace PasswordAPI.Migrations
{
    [DbContext(typeof(PasswordDetailsContext))]
    partial class PasswordDetailsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("PasswordAPI.Models.PasswordDetails", b =>
                {
                    b.Property<int>("PasswordDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ExpirationDate")
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PasswordOwnerName")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordOwnersPhoneNr")
                        .IsRequired()
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("PasswordDetailsId");

                    b.ToTable("PasswordsDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
